apiVersion: v1
kind: Service
metadata:
  name: authenticationnpservice-srv
spec:
  type: NodePort
  selector:
    app: authenticationservice
  ports:
    - name: authenticationservice
      protocol: TCP
      port: 80
      targetPort: 80